# Solid State Project

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## SHO 1D Tight Bing

### Task 1: Hamiltonian Construction

$$
H = -t \sum_n (\ket{n + 1}\bra{n} + \ket{n}\bra{n + 1})
$$

+ Write a program that constructs the Hamiltonian matrix in the periodic boundary condi1ons (PBC), where site 𝑁 is iden1fied with site 0.

+ Modify the code to handle open boundary condi1ons (OBC), where sites 0 and 𝑁 − 1 are not connected.

In [5]:
# PBC 
def pbc_Hamiltonian(n, t = 1):
    H = np.zeros((n, n))
    for i in range(n):
        H[i, (i + 1) % n] = -t
        H[(i + 1) % n, i] = -t
    return H

# OBC
def obc_Hamiltonian(n, t = 1):
    H = np.zeros((n, n))
    for i in range(n - 1):
        H[i, i + 1] = -t
        H[i + 1, i] = -t
    return H

In [7]:
# Example

H_PBC = pbc_Hamiltonian(5)
H_OBC = obc_Hamiltonian(5)

print("Hamiltonian in PBC:")
print(H_PBC)
print("Hamiltonian in OBC:")
print(H_OBC)

Hamiltonian in PBC:
[[ 0. -1.  0.  0. -1.]
 [-1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.]
 [-1.  0.  0. -1.  0.]]
Hamiltonian in OBC:
[[ 0. -1.  0.  0.  0.]
 [-1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.]
 [ 0.  0.  0. -1.  0.]]
